name: deploy

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build the Docker image
        run: |
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }} ${{ secrets.DOCKER_REPOSITORY }}  
          docker build -t ${{ secrets.DOCKER_REPOSITORY }}/whale-wave/ww-bill/ww-bill-client:${{ github.ref_name }}
      # 登录阿里云
#      - name: deploy aliyun
#        uses: appleboy/ssh-action@master
#        with:
#          host: ${{ secrets.HOST }}
#          username: ${{ secrets.USERNAME }}
#          key: ${{ secrets.RSA_KEY }}
#          port: ${{ secrets.PORT }}
#          script: |
#            ls
#            cd whale-wave/ww-bill-service
#            ./deploy.sh
