name: Build and push Docker images

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.DOCKER_REPOSITORY }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Get version
        id: get_version
        run: echo ::set-output name=version::${GITHUB_REF#refs/tags/v}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64
          push: true
          tags: |
            ${{ secrets.DOCKER_REPOSITORY }}/whale-wave/ww-bill/ww-bill-service:${{ steps.get_version.outputs.version }}
            ${{ secrets.DOCKER_REPOSITORY }}/whale-wave/ww-bill/ww-bill-service:latest
